#include "iit_asn1.h"

ASN1_SEQUENCE(IITParams) =
{
    ASN1_SIMPLE(IITParams, mac, ASN1_OCTET_STRING),
    ASN1_OPT(IITParams, pad, ASN1_OCTET_STRING)
}ASN1_SEQUENCE_END(IITParams)

IMPLEMENT_ASN1_FUNCTIONS(IITParams)
IMPLEMENT_ASN1_PRINT_FUNCTION(IITParams)

ASN1_SEQUENCE(IITHeader) =
{
    ASN1_SIMPLE(IITHeader, type, ASN1_OBJECT),
    ASN1_SIMPLE(IITHeader, params, IITParams)
}ASN1_SEQUENCE_END(IITHeader)

IMPLEMENT_ASN1_FUNCTIONS(IITHeader)
IMPLEMENT_ASN1_PRINT_FUNCTION(IITHeader)

ASN1_SEQUENCE(IITStore) =
{
    ASN1_SIMPLE(IITStore, header, IITHeader),
    ASN1_SIMPLE(IITStore, data, ASN1_OCTET_STRING)
}ASN1_SEQUENCE_END(IITStore)

IMPLEMENT_ASN1_FUNCTIONS(IITStore)
IMPLEMENT_ASN1_PRINT_FUNCTION(IITStore)
